import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { NodeRegistry } from './NodeRegistry.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// Generates placeholder node definition files for any missing nodes surfaced by the compiler.
export class AutoNodeGenerator {
  private readonly generatedDir: string;
  private readonly registry: NodeRegistry;

  constructor(registry: NodeRegistry, generatedDir = join(__dirname, 'nodes', 'generated')) {
    this.generatedDir = generatedDir;
    this.registry = registry;

    if (!existsSync(this.generatedDir)) {
      mkdirSync(this.generatedDir, { recursive: true });
    }
  }

  async generateMissingNodes(ids: string[]): Promise<string[]> {
    const created: string[] = [];
    for (const rawId of ids) {
      const id = rawId.trim();
      if (!id) continue;
      const filename = this.sanitizeFileName(id);
      const filePath = join(this.generatedDir, `${filename}.ts`);
      if (existsSync(filePath)) {
        continue;
      }
      const content = this.buildStub(id);
      writeFileSync(filePath, content, 'utf-8');
      created.push(filePath);
      // Register the stub immediately so executions can reference it before reload.
      this.registry.register({
        id,
        description: `Auto-generated placeholder for ${id}`,
        inputs: {},
        outputs: {},
        executor: async () => {
          throw new Error(`Node "${id}" is not implemented yet`);
        },
      });
    }

    if (created.length) {
      // Reload registry to pick up the generated modules.
      await this.registry.ensureLoaded();
    }

    return created;
  }

  private sanitizeFileName(id: string): string {
    return id.replace(/[^a-zA-Z0-9_-]/g, '_');
  }

  private buildStub(id: string): string {
    const description = `Auto-generated placeholder for ${id}`;
    return `// Auto-generated by AutoNodeGenerator. Fill in executor with real logic for "${id}".
import type { WorkflowNodeDefinition } from '../../types.js';

const node: WorkflowNodeDefinition = {
  id: '${id}',
  description: '${description}',
  inputs: {},
  outputs: {},
  executor: async () => {
    throw new Error('Node "${id}" is not implemented yet');
  },
};

export default node;
`;
  }
}
